### ISSUE TITLE
Suggestion: Auto-assign hits

### ISSUE THREAD

**Issue by nukeu666** [rally-the-troops/hammer-of-the-scots#1]
In many cases, when damage assignment is to be done, there is only one choice or outcome possible
If this can be done automatically, it will help speed up async games a lot

1. Hits to assign>=steps remaining : Autoassign all damage, battle ends
2. While(Hits to assign>=(number of units with steps equal to max(steps of all units))) then (assign 1 hit to all units with max steps)
Eg.
4 hits to blocks: 4,3,1 [1 automatic assignment]
3 hits to blocks: 3,3,1 [2 automatic assignment]
1 hit to blocks: 2,2,1 [Player choice]

**Comment by ccxvii** [comment]
I used to do this very early on during development. I did not like it, since it's too easy to miss what happens in battles when many hits applied instantly. It's a trade-off between async and real-time usability, and when the two conflict I have chosen in favor of real-time play.

There are several ideas that would be good for async play that I have not implemented -- like automatic damage assignment and showing an arrow overlay for enemy movements.

I'll have a look at adding an option to auto-assign hits that you can choose when starting a new game. I do not want it to be the default behavior.
